name: niskine
channels:
  - conda-forge
dependencies:
  - python=3.10
  - black
  - mercurial   # for pulling pycurrents repo
  - matplotlib
  - cartopy
  - cmocean
  - numpy
  - pandas
  - pytest
  - scipy
  - tqdm
  - xarray
  - dask
  - bottleneck
  - netcdf4
  - cftime
  - gsw
  - utide
  - eofs
  - python-box
  - metpy
  # the following for pulling SSH data
  - cdsapi
  - cfgrib
  - motuclient
  - pip
  - pip:
    - argopy
    - jupytext
    - palettable
    - "-e git+https://github.com/gunnarvoet/gvpy.git#egg=gvpy"
    - "-e git+https://github.com/modscripps/velosearaptor.git#egg=velosearaptor"
    - "hg+https://currents.soest.hawaii.edu/hgstage/pycurrents/#egg=pycurrents"
    # Install the local niskine package in developer mode
    - "-e ."
